### ISSUE TITLE
Look into making file serving a bit more uniform/dev friendly

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-assets-old#10]
The main thing I'm thinking here is to maybe merge the serve and thumb routes into one, and specify the thumb/size as a query string?

Think this should be discussed on the call.

`api/assets/serve/1234567890?thumb=true`

**Comment by memeteli** [comment]
This needs to be duscussed.

**Comment by memeteli** [comment]
What about the size?
