### ISSUE TITLE
Default values should come from schema

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-assets-old#12]
So no need to hard-code any defaults in the js (e.g. [importaudios.js#L5-L16](https://github.com/adapt-security/adapt-authoring-assets/blob/master/lib/importaudios.js#L5-L16))

**Comment by fkcailiniyazi** [comment]
How I can read assets.schema file and get its value from it?

**Comment by memeteli** [comment]
How can I get default values from schema?

`        const jsonschema = await this.app.waitForModule('jsonschema');
        const defaults = jsonschema.applyDefaults('assets', data = {
            "path": filenameHash,
            "type": 'audio',
            "createdAt": (new Date()).toString(),
            "title": req.fields.title,
            "description": req.fields.description
        });
`

This didn't give me what I expected.

**Comment by memeteli** [comment]
``
