### ISSUE TITLE
maxFileUploadSize can probably have a default value

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-assets-old#2]
Will probably need to discuss to decide on a sensible value for this.

**Comment by taylortom** [comment]
Can't find this hooked up anywhere yet, but think this still stands 😄

**Comment by memeteli** [comment]
As I see from Ingo's code  there is a default value of 1000000.

**Comment by taylortom** [comment]
Not sure how I missed that :smile: 
Minor thing, but the default should changed from a string to a number (think validation might throw an error).

**Comment by memeteli** [comment]
Done.
