### ISSUE TITLE
Revisit API endpoints

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-assets-old#22]
https://docs.google.com/document/d/19veTYxGN96B30pt80gaPam25hxoRkseaxnBpo5sAYLk/edit#
### Existing
```
- `/` `GET`
- `/:id` `PUT`
- `/serve/:id` `GET`
- `/thumb/:id` `GET`
- `/trash/:id` `PUT`
- `/query` `POST`
```
### Suggested?
```
- `/:id?` `GET`
- `/:id` `PUT`, `DELETE`
- `/serve/:id?thumb=true` `GET`
- `/query` `POST`
```

**Comment by memeteli** [comment]
Is there any example for how we add a parameter like "-/:id?thumb=true"?

**Comment by taylortom** [comment]
Where:
- `:id` is the standard parameter
- `?` is the query separator
- `thumb=true` is the query string

You should be able to access `req.query.thumb`, which should give you a value of `true`

If you're using AbstractApiModule, you should also be able to use `req.apiData.query`.

You can read more info here:
https://expressjs.com/en/4x/api.html#req.query

**Comment by memeteli** [comment]
Great, many thanks for this Tipp. 👍
