### ISSUE TITLE
Look into permanent deletion

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-assets-old#24]
Would need to be added in conjunction with #9.

(would remove need for _isDeleted).

**Comment by memeteli** [comment]
At the moment just as the old server, many assets could share the same file repository, so it will be a problem if a file has many parents by deletion.

So should we create a separate file repository for each asset or just prevent user upload the same file uploads again?

**Comment by memeteli** [comment]
I think there is no need to discuss this, I handled it via checking the related file path in DB record if it has multiple pointers then we only need to delete the related DB record, if there is only one pointer, then we will delete both of the asset record and asset file.

> At the moment just as the old server, many assets could share the same file repository, so it will be a problem if a file has many parents by deletion.
> 
> So should we create a separate file repository for each asset or just prevent user upload the same file uploads again?
