### ISSUE TITLE
Composite asset upload

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-assets-old#25]
A user should be able to upload a zip file that contain multiple files. These assets would effectively work as a single item for the purposes of selection and build.

This is not part of MVP requirements and probably requires a more detailed proposal.

https://github.com/adapt-security/adapt-authoring/issues/70

**Comment by taylortom** [comment]
To clarify: this ticket refers to zip files to be treated a single assets (not bulk upload of multiple assets).

It was agreed on the call that this is a useful feature, but not required for MVP.

**Comment by memeteli** [comment]
With query parameter "unzip" now we can decide an uploaded zip file should be unzipped or uploaded as single asset.
