### ISSUE TITLE
Create poster image on video upload (assets module)

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-assets-old#28]
It would be nice to generate the poster image (video placeholder) just on video upload. Initially it's no big deal and can be done together with thumbnail generation. But some work remains to be done when it comes to the component implementation and we may have to offer an option to let the user replace it later on by a custom version.

https://github.com/adapt-security/adapt-authoring/issues/211

**Comment by memeteli** [comment]
Which size for poster image is suggested?

**Comment by memeteli** [comment]
> Which size for poster image is suggested?

I think Ingo has 

> Which size for poster image is suggester?

video full size will be set up as default.

**Comment by memeteli** [comment]
How should we name the API route for the replacement of the poster image?

**Comment by memeteli** [comment]
The poster image will be replaced by selecting an asset, it can be done by `api/assets/:id`, so I am closing this issue.
