### ISSUE TITLE
Error on uploading single asset

### ISSUE THREAD

**Issue by deltanetdan** [adapt-security/adapt-authoring-assets-old#31]
I'm getting an issue when uploading a single asset to [POST] {{server_host}}:{{server_port}}/api/assets

If I try and post a single asset (.jpeg) I get the following error:

`error server status code must be a number`

Could be related to [this](https://github.com/adapt-security/adapt-authoring-assets/blob/master/lib/importimages.js#L29) line.

**Comment by memeteli** [comment]
Could you update to the lastest version and try again?

**Comment by deltanetdan** [comment]
Thanks @fkcailiniyazi that fixes the issue.
