### ISSUE TITLE
Security vulnerabilities need fixing

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-assets-old#34]
https://github.com/adapt-security/adapt-authoring-assets/security

**Comment by memeteli** [comment]
I've not seen any security vulnerabilities, should I do something extra?

**Comment by taylortom** [comment]
Sorry, this was specifically related to GitHub's dependabot alerts: 
<https://github.com/adapt-security/adapt-authoring-assets/network/alerts>
