### ISSUE TITLE
What should we do with Thumbnail for Audio and Zip files

### ISSUE THREAD

**Issue by memeteli** [adapt-security/adapt-authoring-assets-old#36]
Yesterday @taylortom mentioned that only a few assets are shown at frontend, then I've tested locally and it worked fine locally, I'm wondering if it caused because audio and zip file doesn't have a thumbnail.

What should we do with Thumbnails for Audio and Zip files?

**Comment by taylortom** [comment]
Just to confirm, no assets were coming through to the UI for me at all (the assets I had uploaded were all .png images).

**Comment by memeteli** [comment]
Which API have you used for getting an asset?

api/assets/serve/:id (for getting an asset)
api/assets/serve/:id?thumb=true (for getting thumb of asset)
api/assets/query  (for querying assets, by default will show all the assets)

**Comment by memeteli** [comment]
Since we can't create thumbnails for Zip and Audio files, it should be the task for the frontend, so I closed this issue.
